In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [30]:
df = pd.read_csv('churn.csv')

In [31]:
df.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   
3              0     299.4         71       50.90  ...         88        5.26   
4              0     166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  
3               2  False.  
4               3  False.  

[5 rows x 21 columns]

In [32]:
df.shape

(3333, 21)

In [33]:
cols = []
for col in df.columns:
    cols.append(col)

In [34]:
cols

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [35]:
df.describe()

Account Length    Area Code  VMail Message     Day Mins    Day Calls  \
count     3333.000000  3333.000000    3333.000000  3333.000000  3333.000000   
mean       101.064806   437.182418       8.099010   179.775098   100.435644   
std         39.822106    42.371290      13.688365    54.467389    20.069084   
min          1.000000   408.000000       0.000000     0.000000     0.000000   
25%         74.000000   408.000000       0.000000   143.700000    87.000000   
50%        101.000000   415.000000       0.000000   179.400000   101.000000   
75%        127.000000   510.000000      20.000000   216.400000   114.000000   
max        243.000000   510.000000      51.000000   350.800000   165.000000   

        Day Charge     Eve Mins    Eve Calls   Eve Charge   Night Mins  \
count  3333.000000  3333.000000  3333.000000  3333.000000  3333.000000   
mean     30.562307   200.980348   100.114311    17.083540   200.872037   
std       9.259435    50.713844    19.922625     4.310668    50.573847   
min       0.000000     0.000000     0.000000     0.000000    23.200000   
25%      24.430000   166.600000    87.000000    14.160000   167.000000   
50%      30.500000   201.400000   100.000000    17.120000   201.200000   
75%      36.790000   235.300000   114.000000    20.000000   235.300000   
max      59.640000   363.700000   170.000000    30.910000   395.000000   

       Night Calls  Night Charge    Intl Mins   Intl Calls  Intl Charge  \
count  3333.000000   3333.000000  3333.000000  3333.000000  3333.000000   
mean    100.107711      9.039325    10.237294     4.479448     2.764581   
std      19.568609      2.275873     2.791840     2.461214     0.753773   
min      33.000000      1.040000     0.000000     0.000000     0.000000   
25%      87.000000      7.520000     8.500000     3.000000     2.300000   
50%     100.000000      9.050000    10.300000     4.000000     2.780000   
75%     113.000000     10.590000    12.100000     6.000000     3.270000   
max     175.000000     17.770000    20.000000    20.000000     5.400000   

       CustServ Calls  
count     3333.000000  
mean         1.562856  
std          1.315491  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          2.000000  
max          9.000000

In [36]:
df['Churn?'].head()

0    False.
1    False.
2    False.
3    False.
4    False.
Name: Churn?, dtype: object

In [37]:
X = df.iloc[:,:-1]

In [38]:
X.shape

(3333, 20)

In [91]:
Y = df.iloc[:,-1]

In [84]:
Y.shape

(3333,)

In [41]:
X.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  Eve Mins  Eve Calls  \
0             25     265.1        110       45.07     197.4         99   
1             26     161.6        123       27.47     195.5        103   
2              0     243.4        114       41.38     121.2        110   
3              0     299.4         71       50.90      61.9         88   
4              0     166.7        113       28.34     148.3        122   

   Eve Charge  Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  \
0       16.78       244.7           91         11.01       10.0           3   
1       16.62       254.4          103         11.45       13.7           3   
2       10.30       162.6          104          7.32       12.2           5   
3        5.26       196.9           89          8.86        6.6           7   
4       12.61       186.9          121          8.41       10.1           3   

   Intl Charge  CustServ Calls  
0         2.70               1  
1         3.70               1  
2         3.29               0  
3         1.78               2  
4         2.73               3

In [42]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
State             3333 non-null object
Account Length    3333 non-null int64
Area Code         3333 non-null int64
Phone             3333 non-null object
Int'l Plan        3333 non-null object
VMail Plan        3333 non-null object
VMail Message     3333 non-null int64
Day Mins          3333 non-null float64
Day Calls         3333 non-null int64
Day Charge        3333 non-null float64
Eve Mins          3333 non-null float64
Eve Calls         3333 non-null int64
Eve Charge        3333 non-null float64
Night Mins        3333 non-null float64
Night Calls       3333 non-null int64
Night Charge      3333 non-null float64
Intl Mins         3333 non-null float64
Intl Calls        3333 non-null int64
Intl Charge       3333 non-null float64
CustServ Calls    3333 non-null int64
dtypes: float64(8), int64(8), object(4)
memory usage: 520.9+ KB


In [43]:
X.drop(['Phone'],axis=1,inplace=True)

In [44]:
X.shape

(3333, 19)

In [45]:
X.head()

State  Account Length  Area Code Int'l Plan VMail Plan  VMail Message  \
0    KS             128        415         no        yes             25   
1    OH             107        415         no        yes             26   
2    NJ             137        415         no         no              0   
3    OH              84        408        yes         no              0   
4    OK              75        415        yes         no              0   

   Day Mins  Day Calls  Day Charge  Eve Mins  Eve Calls  Eve Charge  \
0     265.1        110       45.07     197.4         99       16.78   
1     161.6        123       27.47     195.5        103       16.62   
2     243.4        114       41.38     121.2        110       10.30   
3     299.4         71       50.90      61.9         88        5.26   
4     166.7        113       28.34     148.3        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  
0               1  
1               1  
2               0  
3               2  
4               3

In [46]:
categorical_features = ['State',"Int'l Plan",'VMail Plan']

In [47]:
X[categorical_features].head()

State Int'l Plan VMail Plan
0    KS         no        yes
1    OH         no        yes
2    NJ         no         no
3    OH        yes         no
4    OK        yes         no

In [48]:
len(X['State'].value_counts())

51

In [49]:
X.drop('State',axis=1,inplace=True)

In [50]:
X['Intl Plan'] = pd.get_dummies(X['Int\'l Plan'],drop_first=True)

In [51]:
X.head()

Account Length  Area Code Int'l Plan VMail Plan  VMail Message  Day Mins  \
0             128        415         no        yes             25     265.1   
1             107        415         no        yes             26     161.6   
2             137        415         no         no              0     243.4   
3              84        408        yes         no              0     299.4   
4              75        415        yes         no              0     166.7   

   Day Calls  Day Charge  Eve Mins  Eve Calls  Eve Charge  Night Mins  \
0        110       45.07     197.4         99       16.78       244.7   
1        123       27.47     195.5        103       16.62       254.4   
2        114       41.38     121.2        110       10.30       162.6   
3         71       50.90      61.9         88        5.26       196.9   
4        113       28.34     148.3        122       12.61       186.9   

   Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0           91         11.01       10.0           3         2.70   
1          103         11.45       13.7           3         3.70   
2          104          7.32       12.2           5         3.29   
3           89          8.86        6.6           7         1.78   
4          121          8.41       10.1           3         2.73   

   CustServ Calls  Intl Plan  
0               1          0  
1               1          0  
2               0          0  
3               2          1  
4               3          1

In [52]:
X.drop('Int\'l Plan',axis=1,inplace=True)

In [53]:
X.head()

Account Length  Area Code VMail Plan  VMail Message  Day Mins  Day Calls  \
0             128        415        yes             25     265.1        110   
1             107        415        yes             26     161.6        123   
2             137        415         no              0     243.4        114   
3              84        408         no              0     299.4         71   
4              75        415         no              0     166.7        113   

   Day Charge  Eve Mins  Eve Calls  Eve Charge  Night Mins  Night Calls  \
0       45.07     197.4         99       16.78       244.7           91   
1       27.47     195.5        103       16.62       254.4          103   
2       41.38     121.2        110       10.30       162.6          104   
3       50.90      61.9         88        5.26       196.9           89   
4       28.34     148.3        122       12.61       186.9          121   

   Night Charge  Intl Mins  Intl Calls  Intl Charge  CustServ Calls  Intl Plan  
0         11.01       10.0           3         2.70               1          0  
1         11.45       13.7           3         3.70               1          0  
2          7.32       12.2           5         3.29               0          0  
3          8.86        6.6           7         1.78               2          1  
4          8.41       10.1           3         2.73               3          1

In [54]:
X['Vmail Plan'] = pd.get_dummies(X['VMail Plan'],drop_first=True)

In [55]:
X.head()

Account Length  Area Code VMail Plan  VMail Message  Day Mins  Day Calls  \
0             128        415        yes             25     265.1        110   
1             107        415        yes             26     161.6        123   
2             137        415         no              0     243.4        114   
3              84        408         no              0     299.4         71   
4              75        415         no              0     166.7        113   

   Day Charge  Eve Mins  Eve Calls  Eve Charge  Night Mins  Night Calls  \
0       45.07     197.4         99       16.78       244.7           91   
1       27.47     195.5        103       16.62       254.4          103   
2       41.38     121.2        110       10.30       162.6          104   
3       50.90      61.9         88        5.26       196.9           89   
4       28.34     148.3        122       12.61       186.9          121   

   Night Charge  Intl Mins  Intl Calls  Intl Charge  CustServ Calls  \
0         11.01       10.0           3         2.70               1   
1         11.45       13.7           3         3.70               1   
2          7.32       12.2           5         3.29               0   
3          8.86        6.6           7         1.78               2   
4          8.41       10.1           3         2.73               3   

   Intl Plan  Vmail Plan  
0          0           1  
1          0           1  
2          0           0  
3          1           0  
4          1           0

In [60]:
X.drop('VMail Plan',axis=1,inplace=True)

In [56]:
for col in X.columns:
    if sum(X[col].isna()) >0:
        print(col)
    else:
        print("No missing values in column : "+col)

No missing values in column : Account Length
No missing values in column : Area Code
No missing values in column : VMail Plan
No missing values in column : VMail Message
No missing values in column : Day Mins
No missing values in column : Day Calls
No missing values in column : Day Charge
No missing values in column : Eve Mins
No missing values in column : Eve Calls
No missing values in column : Eve Charge
No missing values in column : Night Mins
No missing values in column : Night Calls
No missing values in column : Night Charge
No missing values in column : Intl Mins
No missing values in column : Intl Calls
No missing values in column : Intl Charge
No missing values in column : CustServ Calls
No missing values in column : Intl Plan
No missing values in column : Vmail Plan


In [61]:
from sklearn.preprocessing import StandardScaler

In [62]:
scaler = StandardScaler()

In [63]:
X_scaled = scaler.fit_transform(X)

In [65]:
X_scaled

array([[ 0.67648946, -0.52360328,  1.23488274, ..., -0.42793202,
        -0.32758048,  1.6170861 ],
       [ 0.14906505, -0.52360328,  1.30794844, ..., -0.42793202,
        -0.32758048,  1.6170861 ],
       [ 0.9025285 , -0.52360328, -0.59175986, ..., -1.1882185 ,
        -0.32758048, -0.61839626],
       ...,
       [-1.83505538,  1.71881732, -0.59175986, ...,  0.33235445,
        -0.32758048, -0.61839626],
       [ 2.08295458,  1.71881732, -0.59175986, ...,  0.33235445,
         3.05268496, -0.61839626],
       [-0.67974475, -0.52360328,  1.23488274, ..., -1.1882185 ,
        -0.32758048,  1.6170861 ]])

In [66]:
X_scaled = pd.DataFrame(X_scaled,columns=X.columns)

In [67]:
X_scaled.head()

Account Length  Area Code  VMail Message  Day Mins  Day Calls  Day Charge  \
0        0.676489  -0.523603       1.234883  1.566767   0.476643    1.567036   
1        0.149065  -0.523603       1.307948 -0.333738   1.124503   -0.334013   
2        0.902529  -0.523603      -0.591760  1.168304   0.675985    1.168464   
3       -0.428590  -0.688834      -0.591760  2.196596  -1.466936    2.196759   
4       -0.654629  -0.523603      -0.591760 -0.240090   0.626149   -0.240041   

   Eve Mins  Eve Calls  Eve Charge  Night Mins  Night Calls  Night Charge  \
0 -0.070610  -0.055940   -0.070427    0.866743    -0.465494      0.866029   
1 -0.108080   0.144867   -0.107549    1.058571     0.147825      1.059390   
2 -1.573383   0.496279   -1.573900   -0.756869     0.198935     -0.755571   
3 -2.742865  -0.608159   -2.743268   -0.078551    -0.567714     -0.078806   
4 -1.038932   1.098699   -1.037939   -0.276311     1.067803     -0.276562   

   Intl Mins  Intl Calls  Intl Charge  CustServ Calls  Intl Plan  Vmail Plan  
0  -0.085008   -0.601195    -0.085690       -0.427932  -0.327580    1.617086  
1   1.240482   -0.601195     1.241169       -0.427932  -0.327580    1.617086  
2   0.703121    0.211534     0.697156       -1.188218  -0.327580   -0.618396  
3  -1.303026    1.024263    -1.306401        0.332354   3.052685   -0.618396  
4  -0.049184   -0.601195    -0.045885        1.092641   3.052685   -0.618396

In [92]:
Y = Y.map({'True.':1, 'False.':0})

In [94]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Churn?, dtype: int64

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
X_train, X_test,Y_train, Y_test = train_test_split(X ,Y ,test_size=.3,random_state=101)

In [104]:
from sklearn.tree import DecisionTreeClassifier

In [105]:
dtc= DecisionTreeClassifier()

In [106]:
dtc.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [109]:
pred = dtc.predict(X_test) 

In [108]:
from sklearn.metrics import classification_report,confusion_matrix

In [110]:
print(confusion_matrix(pred,Y_test))

[[806  40]
 [ 63  91]]


In [111]:
print(classification_report(pred,Y_test))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94       846
           1       0.69      0.59      0.64       154

    accuracy                           0.90      1000
   macro avg       0.81      0.77      0.79      1000
weighted avg       0.89      0.90      0.89      1000



In [112]:
from sklearn.ensemble import RandomForestClassifier

In [117]:
rfc = RandomForestClassifier(max_depth=5,n_estimators=10,max_features=10)

In [118]:
rfc.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=5, max_features=10, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [119]:
pred_rfc = rfc.predict(X_test)

In [120]:
print(confusion_matrix(pred_rfc,Y_test))

[[853  47]
 [ 16  84]]


In [121]:
print(classification_report(pred_rfc,Y_test))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96       900
           1       0.64      0.84      0.73       100

    accuracy                           0.94      1000
   macro avg       0.81      0.89      0.85      1000
weighted avg       0.95      0.94      0.94      1000



In [122]:
from sklearn.svm import SVC

In [123]:
svc = SVC(C=0.025,kernel='linear')

In [125]:
svc.fit(X_train,Y_train)

SVC(C=0.025, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [126]:
pred_svc_0_025 = svc.predict(X_test)

In [127]:
print(confusion_matrix(pred_svc_0_025,Y_test))

[[869 131]
 [  0   0]]


In [128]:
print(classification_report(pred_svc_0_025,Y_test))

              precision    recall  f1-score   support

           0       1.00      0.87      0.93      1000
           1       0.00      0.00      0.00         0

    accuracy                           0.87      1000
   macro avg       0.50      0.43      0.46      1000
weighted avg       1.00      0.87      0.93      1000



/home/shivam/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [135]:
svc_new = SVC(C=100,kernel='linear')

In [136]:
svc_new.fit(X_train,Y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [137]:
pred_svc= svc_new.predict(X_test)

In [138]:
print(confusion_matrix(pred_svc,Y_test))

[[845 109]
 [ 24  22]]


In [139]:
print(classification_report(pred_svc,Y_test))

              precision    recall  f1-score   support

           0       0.97      0.89      0.93       954
           1       0.17      0.48      0.25        46

    accuracy                           0.87      1000
   macro avg       0.57      0.68      0.59      1000
weighted avg       0.94      0.87      0.90      1000



In [141]:
from sklearn.linear_model import LogisticRegression

In [142]:
lr = LogisticRegression()

In [143]:
lr.fit(X_train,Y_train)

/home/shivam/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [144]:
pred_lr = lr.predict(X_test)

In [145]:
print(confusion_matrix(pred_lr,Y_test))

[[842 116]
 [ 27  15]]


In [146]:
print(classification_report(pred_lr,Y_test))

              precision    recall  f1-score   support

           0       0.97      0.88      0.92       958
           1       0.11      0.36      0.17        42

    accuracy                           0.86      1000
   macro avg       0.54      0.62      0.55      1000
weighted avg       0.93      0.86      0.89      1000

